export const dummyUserTableData = [
    {
        id: 1,
        firstName: 'Vishal',
        lastName: 'Devani',
        companyName: 'ABC Inc.',
        mobileNumber: '1234567890',
        emailAddress: 'vishal.devani@example.com',
        isVerified: true
    },
    {
        id: 2,
        firstName: 'John',
        lastName: 'Smith',
        companyName: 'XYZ Corp.',
        mobileNumber: '2345678901',
        emailAddress: 'john.smith@example.com',
        isVerified: false
    },
    {
        id: 3,
        firstName: 'Emily',
        lastName: 'Brown',
        companyName: '123 Company',
        mobileNumber: '3456789012',
        emailAddress: 'emily.brown@example.com',
        isVerified: true
    },
    {
        id: 4,
        firstName: 'Michael',
        lastName: 'Johnson',
        companyName: '456 Corp.',
        mobileNumber: '4567890123',
        emailAddress: 'michael.johnson@example.com',
        isVerified: true
    },
    {
        id: 5,
        firstName: 'Sarah',
        lastName: 'Wilson',
        companyName: 'DEF Ltd.',
        mobileNumber: '5678901234',
        emailAddress: 'sarah.wilson@example.com',
        isVerified: false
    },
    {
        id: 6,
        firstName: 'David',
        lastName: 'Lee',
        companyName: '789 Corp.',
        mobileNumber: '6789012345',
        emailAddress: 'david.lee@example.com',
        isVerified: false
    },
    {
        id: 7,
        firstName: 'Emma',
        lastName: 'Garcia',
        companyName: 'GHI Inc.',
        mobileNumber: '7890123456',
        emailAddress: 'emma.garcia@example.com',
        isVerified: true
    },
    {
        id: 8,
        firstName: 'Daniel',
        lastName: 'Martinez',
        companyName: 'JKL Corp.',
        mobileNumber: '8901234567',
        emailAddress: 'daniel.martinez@example.com',
        isVerified: true
    },
    {
        id: 9,
        firstName: 'Sophia',
        lastName: 'Lopez',
        companyName: 'MNO Ltd.',
        mobileNumber: '9012345678',
        emailAddress: 'sophia.lopez@example.com',
        isVerified: false
    },
    {
        id: 10,
        firstName: 'James',
        lastName: 'Davis',
        companyName: 'PQR Inc.',
        mobileNumber: '0123456789',
        emailAddress: 'james.davis@example.com',
        isVerified: false
    },
    {
        id: 11,
        firstName: 'Olivia',
        lastName: 'Miller',
        companyName: 'STU Corp.',
        mobileNumber: '9876543210',
        emailAddress: 'olivia.miller@example.com',
        isVerified: true
    },
    {
        id: 12,
        firstName: 'William',
        lastName: 'Rodriguez',
        companyName: 'VWX Ltd.',
        mobileNumber: '8765432109',
        emailAddress: 'william.rodriguez@example.com',
        isVerified: true
    },
    {
        id: 13,
        firstName: 'Ava',
        lastName: 'Martinez',
        companyName: 'YZA Inc.',
        mobileNumber: '7654321098',
        emailAddress: 'ava.martinez@example.com',
        isVerified: false
    },
    {
        id: 14,
        firstName: 'Alexander',
        lastName: 'Hernandez',
        companyName: 'BCD Corp.',
        mobileNumber: '6543210987',
        emailAddress: 'alexander.hernandez@example.com',
        isVerified: true
    },
    {
        id: 15,
        firstName: 'Mia',
        lastName: 'Gonzalez',
        companyName: 'EFG Ltd.',
        mobileNumber: '5432109876',
        emailAddress: 'mia.gonzalez@example.com',
        isVerified: true
    },
    {
        id: 16,
        firstName: 'Ethan',
        lastName: 'Perez',
        companyName: 'HIJ Inc.',
        mobileNumber: '4321098765',
        emailAddress: 'ethan.perez@example.com',
        isVerified: true
    },
    {
        id: 17,
        firstName: 'Isabella',
        lastName: 'Sanchez',
        companyName: 'KLM Corp.',
        mobileNumber: '3210987654',
        emailAddress: 'isabella.sanchez@example.com',
        isVerified: false
    },
    {
        id: 18,
        firstName: 'Alexander',
        lastName: 'Gonzalez',
        companyName: 'NOP Ltd.',
        mobileNumber: '2109876543',
        emailAddress: 'alexander.gonzalez@example.com',
        isVerified: false
    },
    {
        id: 19,
        firstName: 'Sophia',
        lastName: 'Rivera',
        companyName: 'QRS Inc.',
        mobileNumber: '1098765432',
        emailAddress: 'sophia.rivera@example.com',
        isVerified: false
    },
    {
        id: 20,
        firstName: 'Mason',
        lastName: 'Brooks',
        companyName: 'TUV Corp.',
        mobileNumber: '0987654321',
        emailAddress: 'mason.brooks@example.com',
        isVerified: true
    },
    {
        id: 21,
        firstName: 'Amelia',
        lastName: 'Roberts',
        companyName: 'WXY Ltd.',
        mobileNumber: '9876543210',
        emailAddress: 'amelia.roberts@example.com',
        isVerified: true
    },
    {
        id: 22,
        firstName: 'Logan',
        lastName: 'Cook',
        companyName: 'ZAB Inc.',
        mobileNumber: '8765432109',
        emailAddress: 'logan.cook@example.com',
        isVerified: false
    },
    {
        id: 23,
        firstName: 'Evelyn',
        lastName: 'Bailey',
        companyName: 'CDE Corp.',
        mobileNumber: '7654321098',
        emailAddress: 'evelyn.bailey@example.com',
        isVerified: false
    },
    {
        id: 24,
        firstName: 'Lucas',
        lastName: 'James',
        companyName: 'FGH Ltd.',
        mobileNumber: '6543210987',
        emailAddress: 'lucas.james@example.com',
        isVerified: true
    },
    {
        id: 25,
        firstName: 'Abigail',
        lastName: 'Phillips',
        companyName: 'IJK Inc.',
        mobileNumber: '5432109876',
        emailAddress: 'abigail.phillips@example.com',
        isVerified: false
    },
    {
        id: 26,
        firstName: 'Jackson',
        lastName: 'Evans',
        companyName: 'LMN Corp.',
        mobileNumber: '4321098765',
        emailAddress: 'jackson.evans@example.com',
        isVerified: false
    },
    {
        id: 27,
        firstName: 'Charlotte',
        lastName: 'Howard',
        companyName: 'OPQ Ltd.',
        mobileNumber: '3210987654',
        emailAddress: 'charlotte.howard@example.com',
        isVerified: true
    },
    {
        id: 28,
        firstName: 'Daniel',
        lastName: 'Morales',
        companyName: 'RST Inc.',
        mobileNumber: '2109876543',
        emailAddress: 'daniel.morales@example.com',
        isVerified: true
    },
    {
        id: 29,
        firstName: 'Harper',
        lastName: 'Ward',
        companyName: 'UVW Corp.',
        mobileNumber: '1098765432',
        emailAddress: 'harper.ward@example.com',
        isVerified: true
    },
    {
        id: 30,
        firstName: 'Aiden',
        lastName: 'Torres',
        companyName: 'XYZ Ltd.',
        mobileNumber: '0987654321',
        emailAddress: 'aiden.torres@example.com',
        isVerified: true
    },
    {
        id: 31,
        firstName: 'Madison',
        lastName: 'Flores',
        companyName: '123 Inc.',
        mobileNumber: '9876543210',
        emailAddress: 'madison.flores@example.com',
        isVerified: true
    },
    {
        id: 32,
        firstName: 'Elijah',
        lastName: 'Nguyen',
        companyName: '456 Corp.',
        mobileNumber: '8765432109',
        emailAddress: 'elijah.nguyen@example.com',
        isVerified: true
    },
    {
        id: 33,
        firstName: 'Avery',
        lastName: 'King',
        companyName: '789 Ltd.',
        mobileNumber: '7654321098',
        emailAddress: 'avery.king@example.com',
        isVerified: true
    },
    {
        id: 34,
        firstName: 'Grayson',
        lastName: 'Scott',
        companyName: 'ABC Inc.',
        mobileNumber: '6543210987',
        emailAddress: 'grayson.scott@example.com',
        isVerified: true
    },
    {
        id: 35,
        firstName: 'Scarlett',
        lastName: 'Gomez',
        companyName: 'XYZ Corp.',
        mobileNumber: '5432109876',
        emailAddress: 'scarlett.gomez@example.com',
        isVerified: true
    },
    {
        id: 36,
        firstName: 'Logan',
        lastName: 'Hill',
        companyName: '123 Company',
        mobileNumber: '4321098765',
        emailAddress: 'logan.hill@example.com',
        isVerified: true
    },
    {
        id: 37,
        firstName: 'Lily',
        lastName: 'Perez',
        companyName: '456 Corp.',
        mobileNumber: '3210987654',
        emailAddress: 'lily.perez@example.com',
        isVerified: true
    },
    {
        id: 38,
        firstName: 'Owen',
        lastName: 'Collins',
        companyName: '789 Ltd.',
        mobileNumber: '2109876543',
        emailAddress: 'owen.collins@example.com',
        isVerified: true
    },
    {
        id: 39,
        firstName: 'Liam',
        lastName: 'Stewart',
        companyName: 'ABC Inc.',
        mobileNumber: '1098765432',
        emailAddress: 'liam.stewart@example.com',
        isVerified: true
    },
    {
        id: 40,
        firstName: 'Zoe',
        lastName: 'Mitchell',
        companyName: 'XYZ Corp.',
        mobileNumber: '0987654321',
        emailAddress: 'zoe.mitchell@example.com',
        isVerified: true
    },
    {
        id: 41,
        firstName: 'Jackson',
        lastName: 'Rogers',
        companyName: '123 Company',
        mobileNumber: '9876543210',
        emailAddress: 'jackson.rogers@example.com',
        isVerified: true
    },
    {
        id: 42,
        firstName: 'Chloe',
        lastName: 'Price',
        companyName: '456 Corp.',
        mobileNumber: '8765432109',
        emailAddress: 'chloe.price@example.com',
        isVerified: true
    },
    {
        id: 43,
        firstName: 'Carter',
        lastName: 'Ward',
        companyName: '789 Ltd.',
        mobileNumber: '7654321098',
        emailAddress: 'carter.ward@example.com',
        isVerified: true
    },
    {
        id: 44,
        firstName: 'Emma',
        lastName: 'Brooks',
        companyName: 'ABC Inc.',
        mobileNumber: '6543210987',
        emailAddress: 'emma.brooks@example.com',
        isVerified: true
    },
    {
        id: 45,
        firstName: 'Aiden',
        lastName: 'Turner',
        companyName: 'XYZ Corp.',
        mobileNumber: '5432109876',
        emailAddress: 'aiden.turner@example.com',
        isVerified: true
    },
    {
        id: 46,
        firstName: 'Grace',
        lastName: 'Scott',
        companyName: '123 Company',
        mobileNumber: '4321098765',
        emailAddress: 'grace.scott@example.com',
        isVerified: true
    },
    {
        id: 47,
        firstName: 'Ethan',
        lastName: 'Gonzalez',
        companyName: '456 Corp.',
        mobileNumber: '3210987654',
        emailAddress: 'ethan.gonzalez@example.com',
        isVerified: true
    },
    {
        id: 48,
        firstName: 'Hannah',
        lastName: 'Evans',
        companyName: '789 Ltd.',
        mobileNumber: '2109876543',
        emailAddress: 'hannah.evans@example.com',
        isVerified: true
    },
    {
        id: 49,
        firstName: 'Luke',
        lastName: 'Ward',
        companyName: 'ABC Inc.',
        mobileNumber: '1098765432',
        emailAddress: 'luke.ward@example.com',
        isVerified: true
    },
    {
        id: 50,
        firstName: 'Leah',
        lastName: 'Morris',
        companyName: 'XYZ Corp.',
        mobileNumber: '0987654321',
        emailAddress: 'leah.morris@example.com',
        isVerified: true
    }
];

export const dummyProductTableData = [
    {
        id: 1,
        uploadImage: 'assets/images/products/product.jpg',
        productCategory: 'Furniture',
        productType: 'Chair',
        productDisplayName: 'Red Lounge Chair',
        customerProductDescription: 'Modern red lounge chair',
        brandName: 'Comfort Seating',
        exWorkPrice: '150.00',
        byColor: 'Red',
        bySize: ['L'],
        originHsnCode: '9401.61.00.90',
        unitMeasure: 'Piece',
        weight: '12.5 kg',
        dimensions: '80x75x100 cm',
        byGender: 'Unisex',
        material: 'Fabric, Steel',
        productFeatures: 'Ergonomic, Swivel',
        approvalStatus: 'Rejected'
    },
    {
        id: 2,
        uploadImage: 'assets/images/products/product.jpg',
        productCategory: 'Electronics',
        productType: 'Laptop',
        productDisplayName: 'Gaming Laptop Pro',
        customerProductDescription: 'High performance gaming laptop',
        brandName: 'Tech Innovators',
        exWorkPrice: '1200.00',
        byColor: 'Black',
        bySize: ['M'],
        originHsnCode: '8471.30.10.00',
        unitMeasure: 'Piece',
        weight: '2.5 kg',
        dimensions: '35x25x2 cm',
        byGender: 'Unisex',
        material: 'Plastic, Metal',
        productFeatures: '16GB RAM, 1TB SSD, GTX 3080',
        approvalStatus: 'Approved'
    },
    {
        id: 3,
        uploadImage: 'assets/images/products/product.jpg',
        productCategory: 'Clothing',
        productType: 'Shirt',
        productDisplayName: 'White Formal Shirt',
        customerProductDescription: 'Men’s formal white shirt',
        brandName: 'Fashion Hub',
        exWorkPrice: '30.00',
        byColor: 'White',
        bySize: ['M'],
        originHsnCode: '6205.20.00.10',
        unitMeasure: 'Piece',
        weight: '0.3 kg',
        dimensions: '40x30x2 cm',
        byGender: 'Male',
        material: 'Cotton',
        productFeatures: 'Wrinkle-Free, Slim Fit',
        approvalStatus: 'Rejected'
    },
    {
        id: 4,
        uploadImage: 'assets/images/products/product.jpg',
        productCategory: 'Automotive',
        productType: 'Tire',
        productDisplayName: 'All-Season Tire',
        customerProductDescription: 'Durable all-season tire for cars',
        brandName: 'AutoSafe',
        exWorkPrice: '100.00',
        byColor: 'Black',
        bySize: ['R17'],
        originHsnCode: '4011.20.10.00',
        unitMeasure: 'Piece',
        weight: '10.5 kg',
        dimensions: '65x65x25 cm',
        byGender: 'Unisex',
        material: 'Rubber',
        productFeatures: 'All-weather, High Traction',
        approvalStatus: 'Rejected'
    },
    {
        id: 5,
        uploadImage: 'assets/images/products/product.jpg',
        productCategory: 'Home Appliances',
        productType: 'Vacuum Cleaner',
        productDisplayName: 'Smart Vacuum Cleaner',
        customerProductDescription: 'Automated smart vacuum cleaner',
        brandName: 'CleanTech',
        exWorkPrice: '300.00',
        byColor: 'Silver',
        bySize: ['M'],
        originHsnCode: '8508.11.00.00',
        unitMeasure: 'Piece',
        weight: '5 kg',
        dimensions: '30x30x10 cm',
        byGender: 'Unisex',
        material: 'Plastic, Metal',
        productFeatures: 'Smart Navigation, Rechargeable',
        approvalStatus: 'Pending'
    },
    {
        id: 6,
        uploadImage: 'assets/images/products/product.jpg',
        productCategory: 'Toys',
        productType: 'Action Figure',
        productDisplayName: 'Superhero Action Figure',
        customerProductDescription: 'Posable superhero action figure',
        brandName: 'ToyWorld',
        exWorkPrice: '20.00',
        byColor: 'Blue',
        bySize: ['M'],
        originHsnCode: '9503.00.21.00',
        unitMeasure: 'Piece',
        weight: '0.5 kg',
        dimensions: '15x10x5 cm',
        byGender: 'Unisex',
        material: 'Plastic',
        productFeatures: 'Articulated, Collectible',
        approvalStatus: 'Rejected'
    },
    {
        id: 7,
        uploadImage: 'assets/images/products/product.jpg',
        productCategory: 'Tools',
        productType: 'Drill',
        productDisplayName: 'Cordless Drill',
        customerProductDescription: 'Portable cordless drill with battery',
        brandName: 'ToolMaster',
        exWorkPrice: '80.00',
        byColor: 'Yellow',
        bySize: ['M'],
        originHsnCode: '8467.21.00.00',
        unitMeasure: 'Piece',
        weight: '1.8 kg',
        dimensions: '20x20x5 cm',
        byGender: 'Unisex',
        material: 'Plastic, Metal',
        productFeatures: 'Rechargeable, High Torque',
        approvalStatus: 'Rejected'
    },
    {
        id: 8,
        uploadImage: 'assets/images/products/product.jpg',
        productCategory: 'Books',
        productType: 'Novel',
        productDisplayName: 'Mystery Novel',
        customerProductDescription: 'Thrilling mystery novel',
        brandName: 'BookWorld',
        exWorkPrice: '15.00',
        byColor: 'Red',
        bySize: ['S'],
        originHsnCode: '4901.99.00.10',
        unitMeasure: 'Piece',
        weight: '0.4 kg',
        dimensions: '21x14x3 cm',
        byGender: 'Unisex',
        material: 'Paper',
        productFeatures: 'Bestseller, Illustrated',
        approvalStatus: 'Approved'
    },
    {
        id: 9,
        uploadImage: 'assets/images/products/product.jpg',
        productCategory: 'Sports',
        productType: 'Football',
        productDisplayName: 'Professional Football',
        customerProductDescription: 'Standard size football for matches',
        brandName: 'Sporty',
        exWorkPrice: '25.00',
        byColor: 'White',
        bySize: ['5'],
        originHsnCode: '9506.62.00.00',
        unitMeasure: 'Piece',
        weight: '0.6 kg',
        dimensions: '22x22x22 cm',
        byGender: 'Unisex',
        material: 'Synthetic Leather',
        productFeatures: 'Durable, Water-Resistant',
        approvalStatus: 'Pending'
    },
    {
        id: 10,
        uploadImage: 'assets/images/products/product.jpg',
        productCategory: 'Jewelry',
        productType: 'Necklace',
        productDisplayName: 'Gold Necklace',
        customerProductDescription: '24k gold necklace',
        brandName: 'JewelCraft',
        exWorkPrice: '500.00',
        byColor: 'Gold',
        bySize: ['M'],
        originHsnCode: '7113.19.10.00',
        unitMeasure: 'Piece',
        weight: '0.1 kg',
        dimensions: '5x5x1 cm',
        byGender: 'Female',
        material: 'Gold',
        productFeatures: 'Pure Gold, Handcrafted',
        approvalStatus: 'Approved'
    },
    {
        id: 11,
        uploadImage: 'assets/images/products/product.jpg',
        productCategory: 'Gardening',
        productType: 'Plant Pot',
        productDisplayName: 'Ceramic Plant Pot',
        customerProductDescription: 'Decorative ceramic plant pot',
        brandName: 'GardenStyle',
        exWorkPrice: '15.00',
        byColor: 'Green',
        bySize: ['M'],
        originHsnCode: '6913.10.00.00',
        unitMeasure: 'Piece',
        weight: '1.2 kg',
        dimensions: '20x20x20 cm',
        byGender: 'Unisex',
        material: 'Ceramic',
        productFeatures: 'Hand-Painted, Durable',
        approvalStatus: 'Pending'
    },
    {
        id: 12,
        uploadImage: 'assets/images/products/product.jpg',
        productCategory: 'Health',
        productType: 'Vitamin Supplement',
        productDisplayName: 'Multivitamin Tablets',
        customerProductDescription: 'Daily multivitamin supplement',
        brandName: 'HealthPlus',
        exWorkPrice: '25.00',
        byColor: 'White',
        bySize: ['M'],
        originHsnCode: '2106.90.92.00',
        unitMeasure: 'Piece',
        weight: '0.2 kg',
        dimensions: '10x5x5 cm',
        byGender: 'Unisex',
        material: 'Plastic',
        productFeatures: 'Contains Vitamins A-Z, 100 Tablets',
        approvalStatus: 'Approved'
    },
    {
        id: 13,
        uploadImage: 'assets/images/products/product.jpg',
        productCategory: 'Beauty',
        productType: 'Lipstick',
        productDisplayName: 'Matte Lipstick',
        customerProductDescription: 'Long-lasting matte lipstick',
        brandName: 'BeautyLine',
        exWorkPrice: '10.00',
        byColor: 'Red',
        bySize: ['S'],
        originHsnCode: '3304.10.00.00',
        unitMeasure: 'Piece',
        weight: '0.05 kg',
        dimensions: '10x2x2 cm',
        byGender: 'Female',
        material: 'Wax, Pigment',
        productFeatures: 'Long-lasting, Matte Finish',
        approvalStatus: 'Rejected'
    },
    {
        id: 14,
        uploadImage: 'assets/images/products/product.jpg',
        productCategory: 'Kitchen',
        productType: 'Blender',
        productDisplayName: 'High-Speed Blender',
        customerProductDescription: 'High-speed blender with multiple settings',
        brandName: 'KitchenPro',
        exWorkPrice: '150.00',
        byColor: 'Black',
        bySize: ['M'],
        originHsnCode: '8509.40.00.00',
        unitMeasure: 'Piece',
        weight: '3 kg',
        dimensions: '40x20x20 cm',
        byGender: 'Unisex',
        material: 'Plastic, Metal',
        productFeatures: 'Multiple Speed Settings, Dishwasher Safe',
        approvalStatus: 'Pending'
    },
    {
        id: 15,
        uploadImage: 'assets/images/products/product.jpg',
        productCategory: 'Outdoors',
        productType: 'Tent',
        productDisplayName: 'Camping Tent',
        customerProductDescription: 'Waterproof camping tent for 4 people',
        brandName: 'OutdoorGear',
        exWorkPrice: '100.00',
        byColor: 'Green',
        bySize: ['L'],
        originHsnCode: '6306.22.00.00',
        unitMeasure: 'Piece',
        weight: '5 kg',
        dimensions: '60x20x20 cm',
        byGender: 'Unisex',
        material: 'Polyester, Fiberglass',
        productFeatures: 'Waterproof, Easy Setup',
        approvalStatus: 'Approved'
    },
    {
        id: 16,
        uploadImage: 'assets/images/products/product.jpg',
        productCategory: 'Pet Supplies',
        productType: 'Dog Bed',
        productDisplayName: 'Comfortable Dog Bed',
        customerProductDescription: 'Soft and comfortable dog bed',
        brandName: 'PetComfort',
        exWorkPrice: '40.00',
        byColor: 'Brown',
        bySize: ['L'],
        originHsnCode: '6307.90.20.00',
        unitMeasure: 'Piece',
        weight: '1 kg',
        dimensions: '80x60x20 cm',
        byGender: 'Unisex',
        material: 'Fabric, Foam',
        productFeatures: 'Soft, Washable Cover',
        approvalStatus: 'Rejected'
    },
    {
        id: 17,
        uploadImage: 'assets/images/products/product.jpg',
        productCategory: 'Stationery',
        productType: 'Notebook',
        productDisplayName: 'Spiral Notebook',
        customerProductDescription: 'A4 size spiral notebook with 200 pages',
        brandName: 'NoteMaster',
        exWorkPrice: '5.00',
        byColor: 'Blue',
        bySize: ['M'],
        originHsnCode: '4820.10.00.00',
        unitMeasure: 'Piece',
        weight: '0.5 kg',
        dimensions: '30x21x2 cm',
        byGender: 'Unisex',
        material: 'Paper, Metal',
        productFeatures: '200 Pages, Ruled',
        approvalStatus: 'Pending'
    },
    {
        id: 18,
        uploadImage: 'assets/images/products/product.jpg',
        productCategory: 'Footwear',
        productType: 'Sneakers',
        productDisplayName: 'Running Sneakers',
        customerProductDescription: 'Lightweight running sneakers',
        brandName: 'RunFast',
        exWorkPrice: '60.00',
        byColor: 'White',
        bySize: ['M'],
        originHsnCode: '6404.11.00.00',
        unitMeasure: 'Pair',
        weight: '1 kg',
        dimensions: '30x20x10 cm',
        byGender: 'Unisex',
        material: 'Mesh, Rubber',
        productFeatures: 'Lightweight, Breathable',
        approvalStatus: 'Approved'
    },
    {
        id: 19,
        uploadImage: 'assets/images/products/product.jpg',
        productCategory: 'Office Supplies',
        productType: 'Chair',
        productDisplayName: 'Ergonomic Office Chair',
        customerProductDescription: 'Adjustable ergonomic office chair',
        brandName: 'OfficeComfort',
        exWorkPrice: '200.00',
        byColor: 'Black',
        bySize: ['L'],
        originHsnCode: '9401.30.00.00',
        unitMeasure: 'Piece',
        weight: '15 kg',
        dimensions: '120x60x60 cm',
        byGender: 'Unisex',
        material: 'Mesh, Metal',
        productFeatures: 'Adjustable, Lumbar Support',
        approvalStatus: 'Pending'
    },
    {
        id: 20,
        uploadImage: 'assets/images/products/product.jpg',
        productCategory: 'Music',
        productType: 'Guitar',
        productDisplayName: 'Acoustic Guitar',
        customerProductDescription: '6-string acoustic guitar',
        brandName: 'MusicMaster',
        exWorkPrice: '120.00',
        byColor: 'Brown',
        bySize: ['M'],
        originHsnCode: '9202.90.10.00',
        unitMeasure: 'Piece',
        weight: '2.5 kg',
        dimensions: '100x40x10 cm',
        byGender: 'Unisex',
        material: 'Wood',
        productFeatures: '6 Strings, Steel Strings',
        approvalStatus: 'Approved'
    }
];
